logging:
  level:
    org:
      springframework: INFO
    com:
      senla: INFO
jwt:
  expiration: '7'
  authorization: "Authorization"
  secret: "SocialNetworkSecret"
  bearer: "Bearer "
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
role:
  admin: ADMIN
request:
  question: '?'
  host: http://backend:8081
  email: "email"
