logging:
  level:
    org:
      springframework: INFO
    com:
      senla: INFO
jwt:
  expiration: '7'
  authorization: "Authorization"
  secret: "SocialNetworkSecret"
  bearer: "Bearer "
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: http://broker:9092
topic:
  name:
    producer: newTopic
role:
  admin: ADMIN
request:
  question: '?'
  host: http://backend:8081
  email: "email"
  id: "id"
