server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-message: always
  port: '8082'
  tomcat:
    max-swallow-size: -1

logging:
  level:
    org:
      springframework: INFO
    com:
      senla: INFO
request:
  host: http://frontend:8080/api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
role:
  admin: ADMIN
app:
  image:
    file-size: 50
spring:
  servlet:
    multipart:
      max-file-size: ${MINIO_MAX_UPLOAD_FILE_SIZE:100MB}
      max-request-size: ${MINIO_MAX_UPLOAD_FILE_SIZE:100MB}
  minio:
    url: ${MINIO_HOST:http://minio:9000}
    bucket:
      image: ${MINIO_IMAGE_PACKAGE:image}
    access-key: ${MINIO_LOGIN:imageStorage}
    secret-key: ${MINIO_PASS:imageStorage}
  cache:
    type: redis
  redis:
    host: redis
    port: 6379