server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-message: always
  port: '8082'
logging:
  level:
    org:
      springframework: INFO
    com:
      senla: INFO
request:
  host: http://localhost:8080/api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
role:
  admin: ADMIN

spring:
  servlet:
    multipart:
      max-file-size: ${MINIO_MAX_UPLOAD_FILE_SIZE:10MB}
      max-request-size: ${MINIO_MAX_UPLOAD_FILE_SIZE:10MB}
    minio:
      url: ${MINIO_HOST:http://localhost:9000}
      bucket:
        common: ${MINIO_ROOT_PACKAGE:storage}
        image: ${MINIO_PUBLIC_PACKAGE:public}
      access-key: ${MINIO_LOGIN:file0storage}
      secret-key: ${MINIO_PASS:file0storage}