server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-message: always
  port: '8082'
logging:
  level:
    org:
      springframework: INFO
    com:
      senla: INFO
request:
  host: http://frontend:8080